name: OnCICI

on: [push]

jobs:
  build:
    name: Benchmarking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Configuring
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Benchmarking
      run: |
        cd build
        make gbench
        bin/gbench
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Configuring
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Testing
      run: |
        cd build
        make tests
        bin/tests
