name: OnCICI

on: [push]

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Configuring
      run: |
        apt install -y git build-essential cmake ccache
        mkdir build
        cd build
        cmake ..
    - name: Building
      run: make
    - name: Testing
      run: make tests && bin/tests
