name: OnCICI

on: [push]
jobs:     
  build:
    name: Building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@master
    - name: Configuring
      env:
        CC: ${{ matrix.compiler }}
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Building
      run: make
    - name: Testing
      run: make tests && bin/tests
